version: "3.7"

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./src/apis:/myfolder/src/apis
      - ./src/app.js:/myfolder/src/app.js
      - ./src/server.js:/myfolder/src/server.js
    ports:
      - 3000:3000

  my-database:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: "UserName"
      POSTGRES_PASSWORD: "Password"
    ports:
      - 5432:5432
