spring:
  application:
    name: callisto-gateway
  cloud:
    consul:
      enabled: true
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        health-check-path: /actuator/health
        health-check-interval: 30s
        health-check-timeout: 5s
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin-server
          uri: http://localhost:3000
          predicates:
            - Path=/go/**
          filters:
#            - RewritePath=/go/(?<path>.*), /$\{path}
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi, there
                preLogger: true
                postLogger: true
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true


management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
